#ifndef _az_MQTT5_CONNECTION_USER_CONFIG_H
#define _az_MQTT5_CONNECTION_USER_CONFIG_H

#define AZ_MQTT5_CONNECTION_CLIENT_CERTIFICATES_MAX (2)
#define AZ_MQTT5_CONNECTION_MAX_CONNECT_ATTEMPTS (2)

#endif // _az_MQTT5_CONNECTION_USER_CONFIG_H