@startuml
skinparam state {
    BackgroundColor<<APP>> APPLICATION
    BackgroundColor<<STRUCT>> Lavender
    BackgroundColor<<FAIL>> Orange
}

[*] --> az_retry_init
az_retry_init -> application_mqtt_connect
state application_mqtt_connect <<APP>>
application_mqtt_connect --> network_failure
application_mqtt_connect --> service_failure
state network_failure<<FAIL>>
state service_failure<<FAIL>>
network_failure --> application_mqtt_disconnect
service_failure --> application_mqtt_disconnect

state application_mqtt_disconnect<<APP>> {
    [*] --> application_get_az_iot_result
    state application_get_az_iot_result <<APP>>
    application_get_az_iot_result --> az_retry_get_delay : az_iot_result
    az_retry_get_delay --> application_delay : az_retry_needed
    state application_delay <<APP>>
    application_delay --> application_mqtt_connect
    az_retry_get_delay --> [*] : az_failed
}

application_get_az_iot_result : - transport_error
az_retry_get_delay : - az_result
az_retry_get_delay : - random_int

@enduml
