// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

#include <az_static_assert.h>

#include <_az_cfg_extern_include_prefix.h>

#include <limits.h>
#include <stdint.h>

#include <_az_cfg_extern_include_suffix.h>

#include <_az_cfg.h>

AZ_STATIC_ASSERT(-1 == ~0)

AZ_STATIC_ASSERT(CHAR_BIT == 8)
AZ_STATIC_ASSERT(sizeof(uint8_t) == 1)
AZ_STATIC_ASSERT(sizeof(uint8_t) == sizeof(char))
AZ_STATIC_ASSERT(sizeof(char) == sizeof(unsigned char))
AZ_STATIC_ASSERT(sizeof(char) == sizeof(signed char))

AZ_STATIC_ASSERT((uint8_t)'\0' == (uint8_t)0)

AZ_STATIC_ASSERT((uint8_t)'\t' == (uint8_t)9)
AZ_STATIC_ASSERT((uint8_t)'\n' == (uint8_t)10)
AZ_STATIC_ASSERT((uint8_t)'\r' == (uint8_t)13)

AZ_STATIC_ASSERT((uint8_t)' ' == (uint8_t)32)
AZ_STATIC_ASSERT((uint8_t)'!' == (uint8_t)33)
AZ_STATIC_ASSERT((uint8_t)'"' == (uint8_t)34)
AZ_STATIC_ASSERT((uint8_t)'#' == (uint8_t)35)
AZ_STATIC_ASSERT((uint8_t)'$' == (uint8_t)36)
AZ_STATIC_ASSERT((uint8_t)'%' == (uint8_t)37)
AZ_STATIC_ASSERT((uint8_t)'&' == (uint8_t)38)
AZ_STATIC_ASSERT((uint8_t)'\'' == (uint8_t)39)
AZ_STATIC_ASSERT((uint8_t)'(' == (uint8_t)40)
AZ_STATIC_ASSERT((uint8_t)')' == (uint8_t)41)
AZ_STATIC_ASSERT((uint8_t)'*' == (uint8_t)42)
AZ_STATIC_ASSERT((uint8_t)'+' == (uint8_t)43)
AZ_STATIC_ASSERT((uint8_t)',' == (uint8_t)44)
AZ_STATIC_ASSERT((uint8_t)'-' == (uint8_t)45)
AZ_STATIC_ASSERT((uint8_t)'.' == (uint8_t)46)
AZ_STATIC_ASSERT((uint8_t)'/' == (uint8_t)47)

AZ_STATIC_ASSERT((uint8_t)'0' == (uint8_t)48)
AZ_STATIC_ASSERT((uint8_t)'1' == (uint8_t)49)
AZ_STATIC_ASSERT((uint8_t)'2' == (uint8_t)50)
AZ_STATIC_ASSERT((uint8_t)'3' == (uint8_t)51)
AZ_STATIC_ASSERT((uint8_t)'4' == (uint8_t)52)
AZ_STATIC_ASSERT((uint8_t)'5' == (uint8_t)53)
AZ_STATIC_ASSERT((uint8_t)'6' == (uint8_t)54)
AZ_STATIC_ASSERT((uint8_t)'7' == (uint8_t)55)
AZ_STATIC_ASSERT((uint8_t)'8' == (uint8_t)56)
AZ_STATIC_ASSERT((uint8_t)'9' == (uint8_t)57)

AZ_STATIC_ASSERT((uint8_t)':' == (uint8_t)58)
AZ_STATIC_ASSERT((uint8_t)';' == (uint8_t)59)
AZ_STATIC_ASSERT((uint8_t)'<' == (uint8_t)60)
AZ_STATIC_ASSERT((uint8_t)'=' == (uint8_t)61)
AZ_STATIC_ASSERT((uint8_t)'>' == (uint8_t)62)
AZ_STATIC_ASSERT((uint8_t)'?' == (uint8_t)63)
AZ_STATIC_ASSERT((uint8_t)'@' == (uint8_t)64)

AZ_STATIC_ASSERT((uint8_t)'A' == (uint8_t)65)
AZ_STATIC_ASSERT((uint8_t)'B' == (uint8_t)66)
AZ_STATIC_ASSERT((uint8_t)'C' == (uint8_t)67)
AZ_STATIC_ASSERT((uint8_t)'D' == (uint8_t)68)
AZ_STATIC_ASSERT((uint8_t)'E' == (uint8_t)69)
AZ_STATIC_ASSERT((uint8_t)'F' == (uint8_t)70)
AZ_STATIC_ASSERT((uint8_t)'G' == (uint8_t)71)
AZ_STATIC_ASSERT((uint8_t)'H' == (uint8_t)72)
AZ_STATIC_ASSERT((uint8_t)'I' == (uint8_t)73)
AZ_STATIC_ASSERT((uint8_t)'J' == (uint8_t)74)
AZ_STATIC_ASSERT((uint8_t)'K' == (uint8_t)75)
AZ_STATIC_ASSERT((uint8_t)'L' == (uint8_t)76)
AZ_STATIC_ASSERT((uint8_t)'M' == (uint8_t)77)
AZ_STATIC_ASSERT((uint8_t)'N' == (uint8_t)78)
AZ_STATIC_ASSERT((uint8_t)'O' == (uint8_t)79)
AZ_STATIC_ASSERT((uint8_t)'P' == (uint8_t)80)
AZ_STATIC_ASSERT((uint8_t)'Q' == (uint8_t)81)
AZ_STATIC_ASSERT((uint8_t)'R' == (uint8_t)82)
AZ_STATIC_ASSERT((uint8_t)'S' == (uint8_t)83)
AZ_STATIC_ASSERT((uint8_t)'T' == (uint8_t)84)
AZ_STATIC_ASSERT((uint8_t)'U' == (uint8_t)85)
AZ_STATIC_ASSERT((uint8_t)'V' == (uint8_t)86)
AZ_STATIC_ASSERT((uint8_t)'W' == (uint8_t)87)
AZ_STATIC_ASSERT((uint8_t)'X' == (uint8_t)88)
AZ_STATIC_ASSERT((uint8_t)'Y' == (uint8_t)89)
AZ_STATIC_ASSERT((uint8_t)'Z' == (uint8_t)90)

AZ_STATIC_ASSERT((uint8_t)'[' == (uint8_t)91)
AZ_STATIC_ASSERT((uint8_t)'\\' == (uint8_t)92)
AZ_STATIC_ASSERT((uint8_t)']' == (uint8_t)93)
AZ_STATIC_ASSERT((uint8_t)'^' == (uint8_t)94)
AZ_STATIC_ASSERT((uint8_t)'_' == (uint8_t)95)
AZ_STATIC_ASSERT((uint8_t)'`' == (uint8_t)96)

AZ_STATIC_ASSERT((uint8_t)'a' == (uint8_t)97)
AZ_STATIC_ASSERT((uint8_t)'b' == (uint8_t)98)
AZ_STATIC_ASSERT((uint8_t)'c' == (uint8_t)99)
AZ_STATIC_ASSERT((uint8_t)'d' == (uint8_t)100)
AZ_STATIC_ASSERT((uint8_t)'e' == (uint8_t)101)
AZ_STATIC_ASSERT((uint8_t)'f' == (uint8_t)102)
AZ_STATIC_ASSERT((uint8_t)'g' == (uint8_t)103)
AZ_STATIC_ASSERT((uint8_t)'h' == (uint8_t)104)
AZ_STATIC_ASSERT((uint8_t)'i' == (uint8_t)105)
AZ_STATIC_ASSERT((uint8_t)'j' == (uint8_t)106)
AZ_STATIC_ASSERT((uint8_t)'k' == (uint8_t)107)
AZ_STATIC_ASSERT((uint8_t)'l' == (uint8_t)108)
AZ_STATIC_ASSERT((uint8_t)'m' == (uint8_t)109)
AZ_STATIC_ASSERT((uint8_t)'n' == (uint8_t)110)
AZ_STATIC_ASSERT((uint8_t)'o' == (uint8_t)111)
AZ_STATIC_ASSERT((uint8_t)'p' == (uint8_t)112)
AZ_STATIC_ASSERT((uint8_t)'q' == (uint8_t)113)
AZ_STATIC_ASSERT((uint8_t)'r' == (uint8_t)114)
AZ_STATIC_ASSERT((uint8_t)'s' == (uint8_t)115)
AZ_STATIC_ASSERT((uint8_t)'t' == (uint8_t)116)
AZ_STATIC_ASSERT((uint8_t)'u' == (uint8_t)117)
AZ_STATIC_ASSERT((uint8_t)'v' == (uint8_t)118)
AZ_STATIC_ASSERT((uint8_t)'w' == (uint8_t)119)
AZ_STATIC_ASSERT((uint8_t)'x' == (uint8_t)120)
AZ_STATIC_ASSERT((uint8_t)'y' == (uint8_t)121)
AZ_STATIC_ASSERT((uint8_t)'z' == (uint8_t)122)

AZ_STATIC_ASSERT((uint8_t)'{' == (uint8_t)123)
AZ_STATIC_ASSERT((uint8_t)'|' == (uint8_t)124)
AZ_STATIC_ASSERT((uint8_t)'}' == (uint8_t)125)
AZ_STATIC_ASSERT((uint8_t)'~' == (uint8_t)126)
