resources:
  repositories:
      # Update refs to get to newer versions of build tools. Make sure to update
      # refs in all relevant files to apply the changes universally.
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools

# This pipeline does not need to run on merge. It is primarily used for building
# release assets.
trigger: none

# This pipeline does not need to run on PR. The c - client - ci pipeline handles
# validating
pr: none

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: storage
      Artifacts:
        - Name: az_storage_blobs
          Path: blobs