function(generate_map_file map_file_name)
  if(MSVC)
    add_link_options(/MAP)
  elseif(CMAKE_C_COMPILER_ID MATCHES "Clang")
    add_link_options(-Wl,-map,${map_file_name}.map)
  else()
    add_link_options(-Xlinker -Map=${map_file_name}.map)
  endif()
endfunction()