jobs:
  - job: Generate
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: >-
          choco install doxygen.install;
          Write-Host 'setting path...';
          Write-Host "##vso[task.setvariable variable=PATH;]${$env:PATH};";
        displayName: Install Doxygen

      - pwsh: >-
          python eng/docs/fill_docs_template.py
          --InputFile="eng/docs/Doxyfile.template"
          --OutputFile="sdk/$(PackageName)/Doxyfile"
          --PackageName="$(PackageName)"
          --PackageVersion="$(PackageVersion)"
        displayName: Fill in Doxyfile.template

      - pwsh: copy eng/docs/assets/ sdk/$(PackageName)
        displayName: Copy assets to Doxyfile location

      - pwsh: doxygen Doxyfile
        workingDirectory: sdk/$(PackageName)
        displayName: Execute Doxygen

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: sdk/$(PackageName)/html
          artifactName: drop