jobs:
  - job: Generate
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: >-
          choco install doxygen.install;
        displayName: Install Doxygen

      - pwsh: >-
          python eng/docs/generate_docs.py
          --TemplateFile="eng/docs/Doxyfile.template"
          --PackagePath="sdk/$(PackageName)"
          --PackageName="$(PackageName)"
          --PackageVersion="$(PackageVersion)"
          --AssetsPath="eng/docs/assets"
          --DoxygenPath="c:\\program files\\doxygen\\bin\\doxygen.exe"
        displayName: Fill in Doxyfile.template

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: sdk/$(PackageName)/html
          artifactName: drop