jobs:
  - job: Generate
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: choco install doxygen.install
        displayName: Install Doxygen

      - pwsh: >-
          python /eng/docs/fill_docs_template.py
          --InputFile="eng/docs/Doxyfile.template"
          --OutputFile="sdk/$(PackageName)/Doxyfile"
          --PackageName="$(PackageName)"
          --PackageVersion="$(PackageVersion)"
        displayName: Fill in Doxyfile.template

      - pwsh: doxygen Doxyfile
        workingDirectory: sdk/$(PackageName)
        displayName: Execute Doxygen

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: sdk/$(PackageName)/html
          artifactName: drop