jobs:
- job: Build
  strategy:
    matrix:
      Win:
        vm.image: 'windows-2019'
  pool:
    vmImage: $(vm.image)
  steps:
  - checkout: self
    submodules: recursive
  - task: CMake@1
    inputs:
      cmakeArgs: ..
  - task: CMake@1
    inputs:
      cmakeArgs: --build . --target RUN_TESTS
