parameters:
  LiveTestSamples: []

jobs:
  - job: LiveTest
    condition: succeededOrFailed()
    strategy:
      matrix:
        Linux_x64_with_samples:
          vm.image: 'ubuntu-18.04'
          vcpkg.deps: 'curl[ssl]'
          VCPKG_DEFAULT_TRIPLET: 'x64-linux'
          build.args: ' -DTRANSPORT_CURL=ON'
        Win_x86_with_samples:
          vm.image: 'windows-2019'
          vcpkg.deps: 'curl[winssl]'
          VCPKG_DEFAULT_TRIPLET: 'x86-windows-static'
          CMAKE_GENERATOR: 'Visual Studio 16 2019'
          CMAKE_GENERATOR_PLATFORM: Win32
          build.args: ' -DTRANSPORT_CURL=ON'
        Win_x64_with_samples:
          vm.image: 'windows-2019'
          vcpkg.deps: 'curl[winssl]'
          VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
          CMAKE_GENERATOR: 'Visual Studio 16 2019'
          CMAKE_GENERATOR_PLATFORM: x64
          build.args: ' -DTRANSPORT_CURL=ON'
        MacOS_x64_with_samples:
          vm.image: 'macOS-10.15'
          vcpkg.deps: 'curl[ssl]'
          VCPKG_DEFAULT_TRIPLET: 'x64-osx'
          build.args: ' -DTRANSPORT_CURL=ON'

    pool:
      vmImage: $(vm.image)

    steps:
      - template: /eng/pipelines/templates/steps/vcpkg.yml
        parameters:
          VmImageVariableName: vm.image
          DependenciesVariableName: vcpkg.deps

      - template: /eng/pipelines/templates/steps/cmake-build.yml
        parameters:
          BuildArgs: $(build.args)

      - template: /eng/common/TestResources/deploy-test-resources.yml
        parameters:
          ServiceDirectory: '.'

      # Run live tests
      - ${{ each sample in parameters.LiveTestSamples }}:
        - script: ${{ sample.LinuxMacPath }}
          displayName: Live Test ${{ sample.Name }} (Non-Windows)
          condition: not(contains(variables['vm.image'], 'windows'))

        - pwsh: ${{ sample.WindowsPath }}
          displayName: Live Test ${{ sample.Name }} (Windows)
          condition: contains(variables['vm.image'], 'windows')


      - template: /eng/common/TestResources/remove-test-resources.yml
        parameters:
          ServiceDirectory: '.'