jobs:
- job: BuildTest
  strategy:
    matrix:
      Linux_x64:
        vm.image: 'ubuntu-18.04'
        vcpkg.deps: ''
        VCPKG_DEFAULT_TRIPLET: 'x64-linux'
      Win_x86:
        vm.image: 'windows-2019'
        vcpkg.deps: ''
        VCPKG_DEFAULT_TRIPLET: 'x86-windows-static'
        CMAKE_GENERATOR: 'Visual Studio 16 2019'
        CMAKE_GENERATOR_PLATFORM: Win32
      Win_x64:
        vm.image: 'windows-2019'
        vcpkg.deps: ''
        VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
        CMAKE_GENERATOR: 'Visual Studio 16 2019'
        CMAKE_GENERATOR_PLATFORM: x64
      MacOS_x64:
        vm.image: 'macOS-10.14'
        vcpkg.deps: ''
        VCPKG_DEFAULT_TRIPLET: 'x64-osx'
        
      Linux_x64_with_samples:
        vm.image: 'ubuntu-18.04'
        vcpkg.deps: 'curl[ssl]'
        VCPKG_DEFAULT_TRIPLET: 'x64-linux'
        build.args: ' -DBUILD_CURL_TRANSPORT=ON'
      Win_x86_with_samples:
        vm.image: 'windows-2019'
        vcpkg.deps: 'curl[winssl]'
        VCPKG_DEFAULT_TRIPLET: 'x86-windows-static'
        CMAKE_GENERATOR: 'Visual Studio 16 2019'
        CMAKE_GENERATOR_PLATFORM: Win32
        build.args: ' -DBUILD_CURL_TRANSPORT=ON'
      Win_x64_with_samples:
        vm.image: 'windows-2019'
        vcpkg.deps: 'curl[winssl]'
        VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
        CMAKE_GENERATOR: 'Visual Studio 16 2019'
        CMAKE_GENERATOR_PLATFORM: x64
        build.args: ' -DBUILD_CURL_TRANSPORT=ON'
      MacOS_x64_with_samples:
        vm.image: 'macOS-10.14'
        vcpkg.deps: 'curl[ssl]'
        VCPKG_DEFAULT_TRIPLET: 'x64-osx'
        build.args: ' -DBUILD_CURL_TRANSPORT=ON'
  pool:
    vmImage: $(vm.image)
  steps:
  - checkout: self
    submodules: recursive

  # Mac OS specific requirements
  - task: Bash@3
    inputs:
      targetType: inline
      script: |
        sudo xcode-select --switch /Applications/Xcode_9.4.1.app
        echo "xcode path:"
        sudo xcode-select --print-path

        # Expect failure:
        brew install gcc
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

        # Validate that vcpkg bootstrap succeeded
        ./vcpkg version
        if [ $? -ne 0 ]
        then
          echo "./bootstrap-vcpkg.sh FAILED"
          exit 1
        fi

        echo "##vso[task.prependpath]$(pwd)"
        echo "##vso[task.setvariable variable=VCPKG_INSTALLATION_ROOT;]$(pwd)"

    # Execute only for Mac and if there is at least one dependency to be installed
    condition: and(succeeded(), contains(variables['vm.image'], 'macOS'), not(eq(variables['vcpkg.dep'], '')))
    displayName: vcpkg bootstrap


  - script: |
      vcpkg install $(vcpkg.deps)
    displayName: vcpkg install dependencies
    # Execute only if there is at least one dependency to be installed
    condition: and(succeeded(), not(eq(variables['vcpkg.dep'], '')))

  - task: CMake@1
    inputs:
      cmakeArgs: --version
    displayName: cmake version
  - task: CMake@1
    inputs:
      cmakeArgs: $(build.args) ..
    displayName: cmake generate
  - task: CMake@1
    inputs:
      cmakeArgs: --build .
    displayName: cmake build
  - script: |
      ctest -C Debug
    workingDirectory: build
    displayName: ctest
