jobs:
- job: BuildTest
  strategy:
    matrix:
      Linux:
        vm.image: 'ubuntu-18.04'
        vcpkg.deps: 'curl[ssl]'
        VCPKG_DEFAULT_TRIPLET: 'x64-linux'
      Win:
        vm.image: 'windows-2019'
        vcpkg.deps: 'curl[winssl]'
        VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
      MacOS:
        vm.image: 'macOS-10.14'
        vcpkg.deps: 'curl[ssl]'
        VCPKG_DEFAULT_TRIPLET: 'x64-osx'
  pool:
    vmImage: $(vm.image)
  steps:
  - checkout: self
    submodules: recursive
  - script: |
      brew install gcc6
      sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      ./bootstrap-vcpkg.sh
      echo "##vso[task.prependpath]$(pwd)"
      echo "##vso[task.setvariable variable=VCPKG_INSTALLATION_ROOT;]$(pwd)"
    condition: contains(variables['vm.image'], 'macOS')
    displayName: vcpkg bootstrap
  - script: |
      vcpkg install $(vcpkg.deps)
    displayName: vcpkg install dependencies

  - task: CMake@1
    inputs:
      cmakeArgs: --version
    displayName: cmake version
  - task: CMake@1
    inputs:
      cmakeArgs: -Duse_default_uuid=ON ..
    displayName: cmake generate
  - task: CMake@1
    inputs:
      cmakeArgs: --build .
    displayName: cmake build
  - script: |
      ctest -C Debug
    workingDirectory: build
    displayName: ctest
