parameters:
  LiveTestSamples: []

jobs:
  - job: LiveTest
    condition: and(succeededOrFailed(), ne(variables['Skip.Test'], 'true'))
    strategy:
      matrix:
        Win_x64_with_iot_samples:
          OSVmImage: 'windows-2019'
          vcpkg.deps: 'curl[winssl] cmocka paho-mqtt'
          VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
          CMAKE_GENERATOR: 'Visual Studio 16 2019'
          CMAKE_GENERATOR_PLATFORM: x64
          build.args: ' -DTRANSPORT_PAHO=ON'
          test_type: 'iot'

        Linux_x64_with_iot_samples:
          OSVmImage: 'ubuntu-18.04'
          vcpkg.deps: 'curl[ssl] cmocka paho-mqtt'
          VCPKG_DEFAULT_TRIPLET: 'x64-linux'
          build.args: ' -DTRANSPORT_PAHO=ON'
          test_type: 'iot'

    pool:
      vmImage: $(OSVmImage)

    steps:
      - template: /eng/pipelines/templates/steps/vcpkg.yml
        parameters:
          DependenciesVariableName: vcpkg.deps
      - pwsh: |
          Write-Host "##vso[task.setvariable variable=sourcesDir]:$(Build.SourcesDirectory)

      - template: /eng/common/TestResources/deploy-test-resources.yml
        parameters:
          ServiceDirectory: '.'
      
#      - pwsh: |
#          Connect-AzAccount 
 #         $(Build.SourcesDirectory)/sdk/scripts/iot/Generate-X509-Certificate.ps1 `
  #        -sourcesDir $(Build.SourcesDirectory) `
   #       -iothubName "aziotbld-embed-cd" `
    #      -deviceID "aziotbld-c-sample" `
     #     -deviceIDSaS "aziotbld-c-sample-sas"
      #    -dpsName "aziotbld-c-dps" `
       #   -resourceGroupName $env:AZURE_RESOURCEGROUP_NAME `
        #  -location DeploymentOutputs['LOCATION']
#      - task: PowerShell@2
 #       displayName: 'Generate resources for IoT tests'
      #  condition: contains(variables['test_type'], 'iot')
#        inputs:
 #         pwsh: true
  #        filePath: $(Build.SourcesDirectory)/sdk/scripts/iot/Generate-X509-Certificate.ps1 
   #       arguments: >
    #        -sourcesDir $(Build.SourcesDirectory) 
     #       -iothubName "aziotbld-embed-cd" 
      #      -deviceID "aziotbld-c-sample" 
       #     -dpsName "aziotbld-c-dps" 
        #    -resourceGroupName $env:AZURE_RESOURCEGROUP_NAME 
#        env:
 #         VCPKG_DEFAULT_TRIPLET: x64-windows-static
  #        VCPKG_ROOT: $(Agent.TempDirectory)

      - template: /eng/pipelines/templates/steps/cmake-build.yml
        parameters:
          BuildArgs: $(build.args)

      # Run live tests
      - ${{ each sample in parameters.LiveTestSamples }}:
        - script: ${{ sample.NonWindowsPath }}
          displayName: Live Test ${{ sample.Name }} (Non-Windows)
          condition: not(contains(variables['OSVmImage'], 'windows'))
          
        - script: ${{ sample.WindowsPath }}
          displayName: Live Test ${{ sample.Name }} (Windows)
          condition: contains(variables['OSVmImage'], 'windows')

      - template: /eng/common/TestResources/remove-test-resources.yml
        parameters:
          ServiceDirectory: '.'
