parameters:
  LiveTestSamples: []

jobs:
  - job: LiveTest
    condition: and(succeededOrFailed(), ne(variables['Skip.Test'], 'true'))
    strategy:
      matrix:
        Win_x64_with_iot_samples:
          OSVmImage: 'windows-2019'
          vcpkg.deps: 'curl[winssl] cmocka paho-mqtt'
          VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
          CMAKE_GENERATOR: 'Visual Studio 16 2019'
          CMAKE_GENERATOR_PLATFORM: x64
          build.args: ' -DTRANSPORT_PAHO=ON'
          test_type: 'iot'

        Linux_x64_with_iot_samples:
          OSVmImage: 'ubuntu-18.04'
          vcpkg.deps: 'curl[ssl] cmocka paho-mqtt'
          VCPKG_DEFAULT_TRIPLET: 'x64-linux'
          build.args: ' -DTRANSPORT_PAHO=ON'
          test_type: 'iot'

    pool:
      vmImage: $(OSVmImage)

    steps:
      - template: /eng/pipelines/templates/steps/vcpkg.yml
        parameters:
          DependenciesVariableName: vcpkg.deps

      - pwsh: |
           #Uninstall-Module AzureRm
           Get-PSRepository
           Write-Host ("Powershell Module Path:" + $Env:PSModulePath)
           Install-Module -Name Az.IotHub -Scope AllUsers -Force
           Install-Module -Name Az.DeviceProvisioningServices -Scope AllUsers -Force

        displayName: "Install Az Powershell Modules for IotHub and DPS"
      
      - template: /eng/common/TestResources/deploy-test-resources.yml
        parameters:
          ServiceDirectory: '.'
      
      - template: /eng/pipelines/templates/steps/cmake-build.yml
        parameters:
          BuildArgs: $(build.args)

      # Run live tests
      - ${{ each sample in parameters.LiveTestSamples }}:
        - script: ${{ sample.NonWindowsPath }}
          displayName: Live Test ${{ sample.Name }} (Non-Windows)
          condition: not(contains(variables['OSVmImage'], 'windows'))
          
        - script: ${{ sample.WindowsPath }}
          displayName: Live Test ${{ sample.Name }} (Windows)
          condition: contains(variables['OSVmImage'], 'windows')

      - template: /eng/common/TestResources/remove-test-resources.yml
        parameters:
          ServiceDirectory: '.'
