# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*

# Live testing overrides these triggers
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
