stages:
  - stage: Build
    jobs:
      - template: ../jobs/archetype-sdk-client.yml

  # TODO: Check queue time variables
  - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
    - stage: LiveTest
      jobs:
        - template: /eng/pipelines/templates/jobs/archetype-sdk-tests.yml
          parameters:
            LiveTests:
              Storage Blobs:
                LinuxMacPath: ./build/sdk/storage/blobs/samples/blobs_client_example
                WindowsPath: ./build/sdk/storage/blobs/samples/debug/blobs_client_example.exe

  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'), ne(variables['Skip.Release'], 'true')) }}:

    - template: archetype-c-release.yml
      parameters:
        DependsOn:
        - Build