stages:
  - stage: Build
    jobs:
      - template: ../jobs/archetype-sdk-client.yml

  # TODO: Check queue time variables
  - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
    - stage: LiveTest
      jobs:
        - template: /eng/pipelines/templates/jobs/archetype-sdk-tests.yml
          parameters:
            LiveTestSamples:
              - Name: Storage Blobs
                LinuxMacPath: ./build/sdk/storage/blobs/samples/blobs_client_example
                WindowsPath: ./build/sdk/storage/blobs/samples/debug/blobs_client_example.exe

  - ${{ if and(eq(parameters.IsReleaseCandidate, true), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal')) }}:

    - template: archetype-c-release.yml
      parameters:
        DependsOn:
        - Build