stages:
  - stage: Build
    jobs:
      - template: ../jobs/archetype-sdk-client.yml

  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:

    - template: archetype-c-release.yml
      parameters:
        DependsOn:
        - Build