stages:
  - ${{ if not(endsWith(variables['Build.DefinitionName'], ' - tests')) }}:
    - stage: Build
      dependsOn: []
      condition:
      jobs:
        - template: ../jobs/archetype-sdk-client.yml

  - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
    - stage: LiveTest
      dependsOn: []
      jobs:
        - template: /eng/pipelines/templates/jobs/archetype-sdk-tests.yml
          parameters:
            LiveTestSamples:
              - Name: Storage Blobs
                NonWindowsPath: ./build/sdk/samples/storage/blobs/blobs_client_example
                WindowsPath: build\sdk\samples\storage\blobs\debug\blobs_client_example.exe

  - ${{ if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'), not(endsWith(variables['Build.DefinitionName'], ' - tests'))) }}:
    - template: archetype-c-release.yml
      parameters:
        DependsOn:
        - Build