stages:
  - ${{ if not(endsWith(variables['Build.DefinitionName'], ' - tests')) }}:
    - stage: Build
      dependsOn: []
      condition:
      jobs:
        - template: ../jobs/archetype-sdk-client.yml

  - ${{ if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'), not(endsWith(variables['Build.DefinitionName'], ' - tests'))) }}:
    - template: archetype-c-release.yml
      parameters:
        DependsOn:
        - Build